shared:
  image: node:12
  steps:
    - ls
    
jobs:
  start:
    requires: [ ~pr, ~commit ]
    
  sub-1:
    requires: [ ~start ]
    
  sub-2:
    requires: [ ~sub-1 ]
    
  sub-3:
    requires: [ ~sub-2 ]

  end:
    requires: [ ~start, ~sub-1, ~sub-3 ]
