shared:
  image: node:12
  steps:
    - ls
    
jobs:
  start:
    requires: [ ~pr, ~commit ]
    
  sub-1:
    requires: [ ~start ]
    
  sub-2:
    requires: [ ~start ]
    
  sub-3:
    requires: [ ~start ]

  sub-4:
    requires: [ ~start ]

  sub-5:
    requires: [ ~start ]

  sub-6:
    requires: [ ~start ]

  end:
    requires: [ sub-1, sub-2, sub-3, sub-4, sub-5, sub-6 ]
